### PR TITLE
added a connection ok check before returning connection to the pool

### LINKED ISSUE #4: Reconnect when downstream connection is broken
Running the remote storage adapter (RSA) on a deployment of Prometheus 2.5.  Restarted the proxy that this was writing to and the connection never regenerated.  Points stopped reporting to Wavefront, and the RSA wrote until the buffer was full and could not flush.

I would expect the RSA would be able to reconnect to a proxy machine if it sees the connection is dead.

This was observed when data in Wavefront was missing and Prometheus logs were spamming:

level=warn ts=2018-12-07T23:14:41.523353596Z caller=queue_manager.go:230 component=remote queue=0:http://wavefront-stg-adapter/receive msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed."
level=warn ts=2018-12-07T23:14:41.523388415Z caller=queue_manager.go:230 component=remote queue=0:http://wavefront-stg-adapter/receive msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed."

### PR DESCRIPTION
**Pull request by sandeepbhojwani**
Testing Done
- reproduced reconnect issue when connection closed by server by killing server process
- verified the fix

resolves #4

### CODE REVIEW

**Comment by shaoxt** [comment]
We should check the "Flush" in Writer.go also

```
	defer func() {
		bw.Flush()
		w.pool.Return(out, fail)
	}()
```

Suggested change

```
	defer func() {
		var err = bw.Flush()
		if err != nil && !fail {
			fail = true
		}
		w.pool.Return(out, fail)
	}()
```

**Review by vikramraman — APPROVED** [review]

**Comment by vikramraman** [comment]
Thanks for the fix!

**Comment by alfredkrohmer** [comment]
@vikramraman Could you please create a new release+image on docker hub with this fix?

**Comment by vikramraman** [comment]
@devkid Thanks for the bump. Released it.

**Comment by alfredkrohmer** [comment]
Thanks a lot :)

**Pull request merged**
