### PR TITLE
feature: Allowing users to override name of metrics with custom value without applying any transformation to the name itself.

### PR DESCRIPTION
**Pull request by inspiremirnal**
We have this use case where we would like few of our metrics name to not go through transformation. Which don't apply any path conversion, metric prefix and might as well convert to a completely custom name before sending it over to wavefront. 

an example would be to pass on -metrics-name-override metric_name_to_override=new_name_without_transformation,.....

We needed this cause we have numerous dashboards already created , which expects a particular name of time-series to work. Since the  source of those metrics is now changed to Prometheus, rather than changing all the dashboards , we will like to have this feature itself in the metrics pipeline which can take care of few overrides.

### CODE REVIEW

**Comment by inspiremirnal** [comment]
@vikramraman  could you please review the PR and let me know what you think about it ? we are kind of waiting on this feature.

**Review by mmichael — APPROVED** [review]
Looks good to me.

**Comment by ustinov** [comment]
https://github.com/wavefrontHQ/prometheus-storage-adapter/runs/3679579502

**Comment by inspiremirnal** [comment]
@ustinov 

> https://github.com/wavefrontHQ/prometheus-storage-adapter/runs/3679579502

I am not sure why the build is failing, i can see the tests were successful. Is it due to some formatting issue that it wasn't expecting ?

**Pull request merged**
